# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCbuLg23aADPAVL81PDrrqnGfkO8qoaH
"""



import os
os.environ['GOOGLE_API_KEY'] = "AIzaSyADvpyRnnyKupNoddbNv3D4QNqf2eaGRGo"

import google.generativeai as genai

genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

# Model Configuration
MODEL_CONFIG = {
  "temperature": 0.2,
  "top_p": 1,
  "top_k": 32,
  "max_output_tokens": 4096,
}

## Safety Settings of Model
safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  }
]

model = genai.GenerativeModel(model_name = "gemini-pro-vision",
                              generation_config = MODEL_CONFIG,
                              safety_settings = safety_settings)

from pathlib import Path

def image_format(image_path):
    img = Path(image_path)

    if not img.exists():
        raise FileNotFoundError(f"Could not find image: {img}")

    image_parts = [
        {
            "mime_type": "image/jpeg", ## Mime type are PNG - image/png. JPEG - image/jpeg. WEBP - image/webp
            "data": img.read_bytes()
        }
    ]
    return image_parts

def gemini_output(image_path, system_prompt, user_prompt):

    image_info = image_format(image_path)
    input_prompt= [system_prompt, image_info[0], user_prompt]
    response = model.generate_content(input_prompt)
    return response.text

system_prompt = """Welcome to the Retail Product Inventory Management System!

As the shop manager, your role is pivotal in maintaining accurate records of our daily retail inventory. Our system utilizes cutting-edge image analysis technology to assist you in this task. We understand the importance of efficiency and accuracy in managing inventory, and our system is designed to streamline this process for you.

Here's a detailed overview of how our system works:

Image Upload: Your first step is to provide an image containing the products you wish to inventory. This image should capture all the products visible in your shop at a particular moment in time.

Image Analysis: Once you've uploaded the image, our system kicks into action. Through advanced image recognition algorithms, we meticulously analyze the contents of the image. Every product visible in the image is identified and categorized.

Product Enumeration: After identifying the products, our system counts the number of instances of each product present in the image. It carefully tallies the quantity of each product type, ensuring a comprehensive inventory assessment.

Accuracy Consideration: While accuracy is essential, we understand that perfect precision may not always be feasible, especially when dealing with diverse and dynamic retail environments. Therefore, our focus is on providing a reliable estimation based on the visual information present in the image.

Product List Generation: Once the analysis is complete, we generate a detailed list of all the products identified in the image. Alongside each product, you'll find the corresponding count, indicating how many instances of that product were detected.

Record Maintenance: It's important to note that your oversight is crucial in this process. While our system handles the analysis and enumeration, you play a vital role in ensuring the accuracy and integrity of the inventory records. You'll need to review the generated product list and verify its accuracy against the actual inventory in your shop.

Continuous Improvement: We're committed to enhancing the functionality and accuracy of our system continually. Your feedback and insights are invaluable in this journey of improvement. We encourage you to provide us with any feedback or suggestions you may have to further refine our inventory management system.


Please upload an image of your current inventory to begin the analysis.
 """

image_path = "2.jpg"

user_prompt = "user will get the names of product with frequencey in html format and "

page = gemini_output(image_path, system_prompt, user_prompt)

page

print(page)